PRAGMA foreign_keys=ON;
BEGIN TRANSACTION;
INSERT INTO "APP_CONFIG" VALUES(1,'MASTER',0,'NAME','CATEGORY',0);
INSERT INTO "APP_CONFIG" VALUES(2,'CATEGORY',1,'NAME','Animals / Pets',1);
INSERT INTO "APP_CONFIG" VALUES(3,'CATEGORY',1,'NAME','Bags, Baggage, Luggage',2);
INSERT INTO "APP_CONFIG" VALUES(4,'CATEGORY',1,'NAME','Clothing',3);
INSERT INTO "APP_CONFIG" VALUES(5,'CATEGORY',1,'NAME','Collectors Items',4);
INSERT INTO "APP_CONFIG" VALUES(6,'CATEGORY',1,'NAME','Electronics ',5);
INSERT INTO "APP_CONFIG" VALUES(7,'CATEGORY',1,'NAME','Household/Tools ',6);
INSERT INTO "APP_CONFIG" VALUES(8,'CATEGORY',1,'NAME','Jewelry',7);


INSERT INTO "APP_CONFIG" VALUES(10,'SUBCATEGORY',2,'NAME','Birds',1);
INSERT INTO "APP_CONFIG" VALUES(11,'SUBCATEGORY',2,'NAME','Cats',2);
INSERT INTO "APP_CONFIG" VALUES(12,'SUBCATEGORY',2,'NAME','Dogs',3);
INSERT INTO "APP_CONFIG" VALUES(13,'SUBCATEGORY',2,'NAME','Ferrets',4);
INSERT INTO "APP_CONFIG" VALUES(14,'SUBCATEGORY',2,'NAME','Hamsters, Guinea Pigs, etc',5);

INSERT INTO "APP_CONFIG" VALUES(15,'SUBCATEGORY',3,'NAME','Backpack, Knapsack',1);
INSERT INTO "APP_CONFIG" VALUES(16,'SUBCATEGORY',3,'NAME','Briefcase',2);
INSERT INTO "APP_CONFIG" VALUES(17,'SUBCATEGORY',3,'NAME','Canvas, Duffel, Sports Bags',3);
INSERT INTO "APP_CONFIG" VALUES(18,'SUBCATEGORY',3,'NAME','DOPP Kit, Makeup Bag',4);
INSERT INTO "APP_CONFIG" VALUES(19,'SUBCATEGORY',3,'NAME','Garment Bags',5);

INSERT INTO "APP_CONFIG" VALUES(20,'SUBCATEGORY',4,'NAME','Assorted Clothes, Laundry Bags',1);
INSERT INTO "APP_CONFIG" VALUES(21,'SUBCATEGORY',4,'NAME','Belts, Suspenders',2);
INSERT INTO "APP_CONFIG" VALUES(22,'SUBCATEGORY',4,'NAME','Dogs',3);
INSERT INTO "APP_CONFIG" VALUES(23,'SUBCATEGORY',4,'NAME','Blazers, Coats, Jackets, Overcoats',4);
INSERT INTO "APP_CONFIG" VALUES(24,'SUBCATEGORY',4,'NAME','Cumberbuns, Ties, Vests',5);
INSERT INTO "APP_CONFIG" VALUES(25,'SUBCATEGORY',4,'NAME','Dresses, Gowns, Skirts',6);

DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('APP_CONFIG',25);

COMMIT;
